project:
  type: website
  output-dir: docs # command to allow publishing using docs (https://quarto.org/docs/publishing/github-pages.html)


website:

  title: "Evolvo Ergo Sum"
  reader-mode: true
  page-navigation: true
  description: "Ecology, Evolution with a sprinkle of Technology"
  site-url: https://giulianocolosimo.github.com
  repo-url: https://github.com/quarto-dev/quarto-demo
  repo-actions: [issue]
  open-graph:
    locale: en_US
  
  navbar:
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: aboutme.qmd
      - text: "Publications"
        menu: 
          - href: peerreviewed.qmd
            text: "Peer-reviewed"
          - href: nonpeerreviewed.qmd
            text: "Non Peer-reviewed"
      - text: "Projects"
        menu: 
          - href: taco.qmd
            text: "T. A. Co."
      #- text: "Classes"
      #  menu: 
      #    - href: antboc.qmd
      #      text: "Animal Tracking"
      #    - href: biocon.qmd
      #      text: "Conservation Biology"
      - text: "Blog"
        href: blog.qmd
      - text: "Photos"
        href: photos.qmd
      #- text: "Quotes"
      #  href: quotes.qmd
      - text: "Contacts"
        href: contacts.qmd

        
  sidebar:
    logo: "./figures/avatar.jpg"
    pinned: false
    align: center
    style: "docked"
    background: light
    collapse-level: 2
    #contents:
    #  - section: "Projects"
    #    contents: 
    #      - href: taco.qmd
    #        text: "T. A. Co."
      #    - href: inbreedingdepression.qmd
      #      text: "Inbreeding depression"
      #    - href: ngR.qmd
      #      text: "ngR"
      #    - href: gephast.qmd
      #      text: "GEPHAST"

      #- section: "Publications"
      #  title: "Publications"
      #  contents: 
      #    - href: peerreviewed.qmd
      #      text: "Peer-reviewed"
      #    - href: nonpeerreviewed.qmd
      #      text: "Non Peer-reviewed"

    tools:
      - url: "https://www.linkedin.com/in/giulianocolosimo/"
        icon: linkedin
      - icon: github
        url: "https://github.com/GiulianoColosimo"
      - icon: envelope
        url: "mailto:giuliano.colosimo@uniroma2.it"
      - url: "https://drive.proton.me/urls/XTZG4M52RR#mpcdheaxnXE8"
        icon: file-pdf
        
  page-footer:
    left: "© Copyright 2023 Giuliano Colosimo"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspiration for this site comes from [here](https://www.mm218.dev)"
    background: dark
    

format:
  html:
    #theme: [sandstone, _variables.scss]
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    grid:
      sidebar-width: 350px
