---
title: "About Me"
author:
    - name: Giuliano Colosimo
      orcid: 0000-0002-0485-9758
editor: visual
date-modified: last-modified
---

I was born in 1985 and raised in Rome (IT). Always enthusiastic about the outdoors and all critters populating it. I got my primary and secondary education in Rome, but when I got to college I knew I wanted to experience research outside of Italy and Europe. During my master I spent 6 months at Aarhus University (Denmark) thanks to the ERASMUS project. I graduated with a Master in Ecology and Evolution from the University of Rome Tor Vergata. I then decided to get a PhD and started looking for a program that could interest me. I found one at Mississippi State University (Mississippi, USA), and Starkville became home for about 6 years.

I got my PhD degree in December 2016. My project focused on understanding the population dynamics of iguanas inhabiting highly fragmented habitats in the Caribbean region. I focused on two species, the Turks and Caicos Rock Iguana, *Cyclura carinata*, and the Bahamas Rock Iguanas, *Cyclura cychlura*.

After my PhD I stayed in contact with a scientist from the San Diego Zoo Wildlife Association (SDZWA) who had been a member of my committee. He was interested in writing a project on the pink iguanas of the Galapagos, and I was too. We teamed up to collaborate with a colleague from the University of Rome Tor Vergata. That project was funded thanks to a generous donation through the SDZWA and granted me the possibility to do a PostDoc for 5 years and to keep doing my research in the Caribbean as well as in the Galapagos.

## Current position

Research associate \@ University of Rome Tor Vergata

## Education and professional experience

| What | Where | When |
|------------------|------------------------------------|-----------------|
| Research associate | University of Rome Tor Vergata, Rome (IT) | 2022-2025 |
| PostDoctoral Fellowship | San Diego Zoo Wildlife Alliance, San Diego, CA (USA) | 2017-2022 |
| PhD in Conservation Genetics | Mississippi State University, Mississippi State, MS (USA) | 2011-2016 |
| MS in Ecology and Evolution | University of Rome Tor Vergata, Rome (IT) | 2008-2010 |
| BS in Ecology | University of Rome Tor Vergata, Rome (IT) | 2004-2007 |
