---
title: "Evolvo Ergo Sum"
subtitle: "Jesus told me *Come forth, and you will have eternal life!* I came fifth, and I got a toaster!"
#author: Giuliano Colosimo
#date: 2022-09-14 
# "`r Sys.Date()`"
---

## Welcome!

This is where I keep my thoughts, projects, publications, research work, and ideas organized. Well, organized is a rather big word. At any rate, welcome, hope you will find something interesting, eventually.


I’m a research associate working at the University of Rome Tor Vergata. One of the main aspects of my current research is **T. A. Co.** (Tracking Animal and Conservation) project. The project aims at developing an integrated, versatile, miniaturised and cost-effective system for the remote monitoring of endangered animal species from even disconnected and difficult to access areas. This system will allow to acquire data relating to the welfare of individuals and populations threatened directly and indirectly by anthropic activities while measuring important ecological parameters. As a faculty of Tor Vergata University, I am also responsible for teaching classes and mentoring/tutoring students.







