---
title: "Evolvo Ergo Sum"
subtitle: "Jesus told me: *Come forth, and you will have eternal life*! I came fifth, and I got a toaster!"
author:
    - name: Giuliano Colosimo
      orcid: 0000-0002-0485-9758
date: "2023-03-31"
date-modified: last-modified
---

## Welcome!

This is where I keep track of my projects, publications, research, work, and ideas. While helping me to keep my thoughts organized, this space is also an opportunity to share them with the rest of the world. Not that the world needs my thoughts, but I most definitely could benefit from the world's feedback. At any rate, welcome! Hope you will find something interesting, eventually.

### A brief introduction.

I am an evolutionary and conservation biologist and a Steering Committee member of the IUCN-SSC-Iguana Specialist Group (appointment from 2017 till 2025).

From 2011 to 2016 I taught and conducted research at Mississippi State University (MSU, Mississippi, USA). My dissertation, with a focus in conservation genetics, tackled, using molecular tools, the population dynamic of small and isolated populations of endangered and critically endangered iguanas in the Bahamian Archipelagoes.

After obtaining my PhD title at MSU, I continued my research career as a PostDoc Research Fellow with the San Diego Zoo Wildlife Alliance (SDZWA, California, USA). My fellowship was financed by a scholarship worth $500K and funded by the Kenneth and Anne Griffin Foundation. My research focused on the testing and application of a custom-made system for the remote monitoring of critically endangered iguanas from difficult to access areas in the Galapagos.

From 2022 to 2025 I held the role of non-tenure track researcher at the Department of Biology at the University of Rome Tor Vergata. I am the Principal Investigator in a program for the development of a second generation of integrated, miniaturized, versatile and low-cost system for the remote monitoring of animal species at risk of extinction. The system allows not only to collect real-time data on the position of the tagged individual, but also to monitor physiological and environmental parameters useful for assessing the behavior and welfare of the individual. The multidisciplinary nature of this project has promoted a high level of collaboration with national and international partners.

My research interests encompass biogeography, molecular phylogeny, genetic structure of populations, movement and behavioral ecology, and bioinformatics. Given that my research has consistently involved a substantial field component for the collection of biological samples, I have developed extensive experience in organizing and conducting data collection missions in the field.





### Navigation tips.

If you want to write me, or you need quick access to my CV or some of my linked accounts you can click on the icons located right below my picture, in the upper left side corner. Use the top navigation bar to know more about me, my research, my publications, some of the things I share on my blog, or simply to switch to Dark Mode (highly recommended). I most recently joined the <a rel="me" href="https://mastodon.social/@cinghio">Mastodon</a> community and you can follow me there as well.




