---
title: "Quotes"
editor: visual
author: Giuliano Colosimo
date: 2022-09-29 
---

“I'm sorry, but I don't want to be an emperor. That's not my business. I don't want to rule or conquer anyone. I should like to help everyone if possible; Jew, Gentile, black man, white. We all want to help one another. Human beings are like that. We want to live by each other's happiness, not by each other's misery. We don't want to hate and despise one another. In this world there is room for everyone, and the good earth is rich and can provide for everyone. The way of life can be free and beautiful, but we have lost the way. Greed has poisoned men's souls, has barricaded the world with hate, has goose-stepped us into misery and bloodshed. We have developed speed, but we have shut ourselves in. Machinery that gives abundance has left us in want. Our knowledge has made us cynical; our cleverness, hard and unkind. We think too much and feel too little. More than machinery, we need humanity. More than cleverness, we need kindness and gentleness. Without these qualities, life will be violent and all will be lost. The airplane and the radio have brought us closer together. The very nature of these inventions cries out for the goodness in men; cries out for universal brotherhood; for the unity of us all. Even now my voice is reaching millions throughout the world, millions of despairing men, women, and little children, victims of a system that makes men torture and imprison innocent people. To those who can hear me, I say, do not despair. The misery that is now upon us is but the passing of greed, the bitterness of men who fear the way of human progress. The hate of men will pass, and dictators die, and the power they took from the people will return to the people. And so long as men die, liberty will never perish. Soldiers! Don't give yourselves to brutes, men who despise you, enslave you; who regiment your lives, tell you what to do, what to think and what to feel! Who drill you, diet you, treat you like cattle, use you as cannon fodder. Don't give yourselves to these unnatural men - machine men with machine minds and machine hearts! You are not machines, you are not cattle, you are men! You have the love of humanity in your hearts! You don't hate! Only the unloved hate; the unloved and the unnatural. Soldiers! Don't fight for slavery! Fight for liberty! In the seventeenth chapter of St. Luke, it is written that the kingdom of God is within man, not one man nor a group of men, but in all men! In you! You, the people, have the power, the power to create machines, the power to create happiness! You, the people, have the power to make this life free and beautiful, to make this life a wonderful adventure. Then in the name of democracy, let us use that power. Let us all unite. Let us fight for a new world, a decent world that will give men a chance to work, that will give youth a future and old age a security. By the promise of these things, brutes have risen to power. But they lie! They do not fulfill that promise. They never will! Dictators free themselves but they enslave the people. Now let us fight to fulfill that promise. Let us fight to free the world! To do away with national barriers! To do away with greed, with hate and intolerance! Let us fight for a world of reason, a world where science and progress will lead to all men's happiness. Soldiers, in the name of democracy, let us all unite!” Charlie Chaplin - The Great Dictator

Non-reproducible single occurrences are of no significance to science." Karl Popper - Buffalo, Vince. Bioinformatics Data Skills (p. 36). O'Reilly Media. Kindle Edition.

"Since the computer is a sharp enough tool to be really useful, you can cut yourself on it. " The Technical Skills of Statistics (1964) John Tukey - Buffalo, Vince. Bioinformatics Data Skills (p. 38). O'Reilly Media. Kindle Edition.

"To consult the statistician after an experiment is finished is often merely to ask him to conduct a post mortem examination. He can perhaps say what the experiment died of." R.A. Fisher - Buffalo, Vince. Bioinformatics Data Skills (p. 43). O'Reilly Media. Kindle Edition.

"Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it." Brian Kernighan - Buffalo, Vince. Bioinformatics Data Skills (p. 44). O'Reilly Media. Kindle Edition.

"The best way to predict the future is to invent it!" X-Files S_3.1

"Statisticamente tutto si spiega, personalmente tutto si complica." Daniel Pennac

"Capito quando è difficile dare valore alle emozioni vere quando hai intesta tutti gli impicci quotidiani?" Zerocalcare - Kobane Calling

"Fin quando esisterà qualcuno che rischia per andare a far giocare dei bambini dimenticati, non mi farà sentire complice l'appartenere al terribile genere umano." Roberto Saviano, sulla liberazione di Silvia Romano, 2020-05-10

"La vita di un puntuale è un inferno di solitudini immeritate" Stefano Benni - Achille Pie Veloce

"E se dobbiamo batterci per un futuro migliore, non dobbiamo conoscere il nostro passato e riconciliarci con esso?" Jonathan Safran Foer - Ogni Cosa e Illuminata.

"L'autocoscienza umana ha prodotto quella perpetua insoddisfazione che la filosofia ha cercato invano di curare. " John Gray - Filosofia felina

"Mentre i gatti vivono seguendo la propria natura, gli uomini la reprimono. Il che -paradossalmente- è nella loro natura, al pari dell'eterna fascinazione per le barbarie". John Gray - Filosofia felina

"Quando qualcuno afferma che il suo scopo nella vita è essere felice, in realtà sta dicendo che non lo è: vede la felicità come un progetto e cerca la propria realizzazione in un futuro indeterminato. Il presente scivola via e si insinua l'ansia. Persone simili temono che i propri progressi verso quella condizione futuro vengano intralciati dagli eventi; così si rivolgono alla filosofia o --ai nostri tempi-- alla psicoterapia, che promettono di alleviare quell'inquietudine." John Gray - Filosofia felina
 
---
 
"Quando gli uomini non hanno futuro, si aggrappano al passato"

"Se non puoi essere la penna per scrivere la felicità di qualcuno, cerca di essere la gomma per cancellarne la tristezza."

"Raccontare per non morire diventa il senso dello scrivere."
